### ISSUE TITLE
Pretrained classifiers

### ISSUE THREAD

**Issue by jannicozaech** [TimoK93/ApLift#1]
First, thank you for making the code for this great project available.

The link to the pretrained classifier in your readme is currently not working, would it be possible to get the weights for these models?

**Comment by TimoK93** [comment]
Hi Jan-Nico. Thanks for your interest and for reporting the issue. The link was slightly wrong, but now it should be fixed with commit #732070175ab6bf76db5b0c793cdb4a1fb5d235d7 !

Best,
Timo
