### ISSUE TITLE
 [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xiaoqianbi123** [TimoK93/ApLift#2]
python3: can't open file 'eval_code/Scripts/run_MOTChallenge.py'.
how can i get this .py file?

**Comment by TimoK93** [comment]
Hello,

thank you for the interest in ApLift. It was stored as a Github-Submodule. In the latest version, i checked out and hard-copied the code to the repository. May now you need to adjust the references in the scripts for your purposes.

Best,
Timo

**Comment by xiaoqianbi123** [comment]
Thank you very much!
